### DISCUSSION TITLE
Deprecation of Operation.operationName

### DISCUSSION THREAD

**Discussion by danielsyang** [urql-graphql/urql#1267] [Q&A] [answered]
Hey,

I'm checking out this library for the first time and I'm currently using React-Native + Urql in my project.
However I'm facing a warning about a deprecation of a property called `Operation.operationName` and it says I should use `Operation.kind` instead.
I'm having a hard time trying to figure out why it's happening since I generated my queries using codegen 

```
generates:
  generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-urql"
 ```

So I really don't know where to start debugging this to begin with since I'm pretty much just querying in the most simple way

```
  const [result] = useSendTwilioSmsCodeQuery({
    variables: { cellphone: { number: getValues().cellphone } },
    pause: getValues().cellphone === "",
  })
```

and this is my query:
```
query SendTwilioSmsCode($cellphone: Cellphone!) {
  sendSMSCodeToTwilio(cellphone: $cellphone)
}
```

and these are the versions of all libraries that I'm  using
```
    "react-native": "0.63.3",
    "urql": "^1.11.4",
    "graphql": "^15.4.0",
```

Thank you all
