### DISCUSSION TITLE
Issue with Postgraphile

### DISCUSSION THREAD

**Discussion by paulm17** [urql-graphql/urql#2358] [Q&A] [answered]
Hi there,

I'm trying to get urql to run with postgraphile.

I'm getting the following:

```
TypeError: n.executeQuery is not a function
    at /Users/paul/Share/development/[project]/node_modules/urql/dist/urql.js:171:15
    at Object.useMemo (/Users/paul/Share/development/[project]/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:4810:19)
    at Object.useMemo (/Users/paul/Share/development/[project]/node_modules/react/cjs/react.development.js:1675:21)
    at Object.useQuery (/Users/paul/Share/development/[project]/node_modules/urql/dist/urql.js:167:13)
    at useAllCategoriesQuery (webpack-internal:///./app/graphql/generated/index.tsx:51:44)
    at Category (webpack-internal:///./app/modules/discourse/main/category/index.tsx:18:96)
    at renderWithHooks (/Users/paul/Share/development/[project]/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5280:16)
    at renderIndeterminateComponent (/Users/paul/Share/development/[project]/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5353:15)
    at renderElement (/Users/paul/Share/development/[project]/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5535:7)
    at renderNodeDestructive (/Users/paul/Share/development/[project]/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5674:11)
```

Here is my codegen:

```
overwrite: true
schema: "http://localhost:5000/graphql"
documents:
  - "app/**/*.graphql"
generates:
  app/graphql/types/types.d.ts:
    config:
      defaultMapper: Partial<{T}>
      maybeValue: T | undefined
    plugins:
      - typescript
      - typescript-resolvers
  app/graphql/generated/index.tsx:
    config:
      defaultMapper: Partial<{T}>
      maybeValue: T | undefined
      reactApolloVersion: 3
      withHooks: true
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-urql"
```

What is this a symptom of?  I've taken an existing install using Dgraph that I had working.  I'm not understanding why I have this issue.

Thanks
